/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup Status */
        get: operations["setup_status_api_v1_setup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Companies */
        get: operations["search_companies_api_v1_companies_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cik}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Detail */
        get: operations["company_detail_api_v1_companies__cik__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cik}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Metrics */
        get: operations["company_metrics_api_v1_companies__cik__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cik}/statements/{statement}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Statement */
        get: operations["company_statement_api_v1_companies__cik__statements__statement__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cik}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Facts */
        get: operations["company_facts_api_v1_companies__cik__facts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{cik}/metrics/{metric}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metric Revisions */
        get: operations["metric_revisions_api_v1_companies__cik__metrics__metric__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Companies */
        get: operations["compare_companies_api_v1_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sync Runs */
        get: operations["list_sync_runs_api_v1_sync_runs_get"];
        put?: never;
        /** Create Sync Run */
        post: operations["create_sync_run_api_v1_sync_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompanyDetail */
        CompanyDetail: {
            /** Cik */
            cik: string;
            /** Name */
            name: string;
            /** Supported */
            supported: boolean;
            /** Accounting Standard */
            accounting_standard: string | null;
            /** Tickers */
            tickers: components["schemas"]["SecurityOut"][];
            /** Sic */
            sic: string | null;
            /** Fiscal Year End */
            fiscal_year_end: string | null;
            /** Is Active */
            is_active: boolean;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Coverage Reason */
            coverage_reason?: string | null;
        };
        /** CompanySummary */
        CompanySummary: {
            /** Cik */
            cik: string;
            /** Name */
            name: string;
            /** Supported */
            supported: boolean;
            /** Accounting Standard */
            accounting_standard: string | null;
            /** Tickers */
            tickers: components["schemas"]["SecurityOut"][];
        };
        /** CompareOut */
        CompareOut: {
            /** Frequency */
            frequency: string;
            /** Companies */
            companies: components["schemas"]["CompanySummary"][];
            /** Series */
            series: {
                [key: string]: {
                    [key: string]: components["schemas"]["MetricPointOut"][];
                };
            };
        };
        /** FactOut */
        FactOut: {
            /** Id */
            id: string;
            /** Taxonomy */
            taxonomy: string;
            /** Concept */
            concept: string;
            /** Label */
            label: string | null;
            /** Unit */
            unit: string;
            /** Period Start */
            period_start: string | null;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Value */
            value: string;
            /** Accession */
            accession: string;
            /** Form */
            form: string;
            /**
             * Filed
             * Format: date
             */
            filed: string;
            /** Fiscal Year */
            fiscal_year: number | null;
            /** Fiscal Period */
            fiscal_period: string | null;
            /** Frame */
            frame: string | null;
            /** Source Url */
            source_url: string;
        };
        /** FactsPage */
        FactsPage: {
            /** Items */
            items: components["schemas"]["FactOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MetricPointOut */
        MetricPointOut: {
            /** Metric */
            metric: string;
            /** Name En */
            name_en: string;
            /** Name Zh */
            name_zh: string;
            /** Statement */
            statement: string;
            /** Frequency */
            frequency: string;
            /** Period Start */
            period_start: string | null;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Fiscal Year */
            fiscal_year: number | null;
            /** Fiscal Period */
            fiscal_period: string | null;
            /** Value */
            value: string;
            /** Unit */
            unit: string;
            /** Is Derived */
            is_derived: boolean;
            /** Quality */
            quality: string;
            /**
             * Revision Count
             * @default 1
             */
            revision_count: number;
            source: components["schemas"]["SourceOut"];
        };
        /** MetricSeriesOut */
        MetricSeriesOut: {
            company: components["schemas"]["CompanySummary"];
            /** Frequency */
            frequency: string;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["MetricPointOut"][];
            };
            /** Unavailable */
            unavailable?: string[];
        };
        /** SecurityOut */
        SecurityOut: {
            /** Ticker */
            ticker: string;
            /** Exchange */
            exchange: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** SetupStatus */
        SetupStatus: {
            /** Sec Configured */
            sec_configured: boolean;
            /** Database Connected */
            database_connected: boolean;
            /** Data Dir */
            data_dir: string;
            /** Free Gib */
            free_gib: number;
            /**
             * Disk Requirement Gib
             * @default 60
             */
            disk_requirement_gib: number;
            /** Company Count */
            company_count: number;
            /** Supported Company Count */
            supported_company_count: number;
            latest_sync: components["schemas"]["SyncRunOut"] | null;
        };
        /** SourceOut */
        SourceOut: {
            /** Accession */
            accession: string | null;
            /** Form */
            form: string | null;
            /** Filed */
            filed: string | null;
            /** Url */
            url: string | null;
            /** Lineage */
            lineage?: {
                [key: string]: unknown;
            }[];
        };
        /** StatementOut */
        StatementOut: {
            company: components["schemas"]["CompanySummary"];
            /** Statement */
            statement: string;
            /** Frequency */
            frequency: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            }[];
        };
        /** SyncRunCreate */
        SyncRunCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "bulk" | "top100" | "company";
            /** Cik */
            cik?: string | null;
        };
        /** SyncRunOut */
        SyncRunOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Cik */
            cik: string | null;
            /** Status */
            status: string;
            /** Progress Current */
            progress_current: number;
            /** Progress Total */
            progress_total: number | null;
            /** Message */
            message: string | null;
            /** Error */
            error: string | null;
            /** Source Etag */
            source_etag: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    setup_status_api_v1_setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    search_companies_api_v1_companies_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_detail_api_v1_companies__cik__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cik: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_metrics_api_v1_companies__cik__metrics_get: {
        parameters: {
            query?: {
                frequency?: string;
                metric?: string[] | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                cik: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSeriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_statement_api_v1_companies__cik__statements__statement__get: {
        parameters: {
            query?: {
                frequency?: string;
            };
            header?: never;
            path: {
                cik: string;
                statement: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_facts_api_v1_companies__cik__facts_get: {
        parameters: {
            query?: {
                concept?: string | null;
                form?: string | null;
                unit?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                cik: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metric_revisions_api_v1_companies__cik__metrics__metric__revisions_get: {
        parameters: {
            query: {
                period_end: string;
                frequency?: string;
            };
            header?: never;
            path: {
                cik: string;
                metric: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricPointOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_companies_api_v1_compare_get: {
        parameters: {
            query: {
                cik: string[];
                metric?: string[] | null;
                frequency?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sync_runs_api_v1_sync_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sync_run_api_v1_sync_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
